### ISSUE TITLE
Elasticsearch 7.x compatibility

### ISSUE THREAD

**Issue by plastikschnitzer** [claygregory/munin-elasticsearch#9]
Hi,

just wanted to say I tested it with Elasticsearch 7.x and its working out of the box! Maybe you want to update readme.md?

Best regards,
Plastikschnitzer

**Comment by claygregory** [comment]
Hi @plastikschnitzer— Thanks for the note, that's great to hear! I have updated the readme.md to include 7.x compatibility.
